app/js/api/Profile.js
app/js/api/__tests__/Profile-test.js
app/js/components/notification/UserNotification.jsx
app/js/stores/CurrentProfileStore.js
app/js/stores/SelfStore.js
app/js/stores/__tests__/CurrentProfileStore-test.js
karma.conf.js
package.json

Discovery page loads with images, provided common is built against
concomitant ozp-center change. Notifications are present but not yet
deleteable. Quickview comes up but with no real content as it requires
additional DRF endpoints. Note that this commit also includes an update
to the unit test reporting to make the output more human-readable.

feat(discovery): Preliminary integration of discovery page OZBE3

---

app/js/api/Profile.js
app/js/components/profile/ProfileWindow.jsx

OZBE19 = ozone-development/ozp-backend#19

feat(profile): Hook up profile modal OZBE19

---

app/OzoneConfig.js

This change will add the hud and webtop site ids

Adding metrics webtop and hud site ids as configuration

---

app/js/api/Profile.js
app/js/stores/SelfStore.js
package.json

OZBE21 = ozone-development/ozp-backend#21
OZBE35 = ozone-development/ozp-backend#35
Also update roles checkers.

feat(quickview): Convert backend data with humps OZBE#21, 35

---

app/OzoneConfig.js
app/js/components/contacts/ContactsWindow.jsx
app/styles/_contacts-window.scss
app/styles/commons.scss

Created a modal to house links to all forms of contacts in Center and Hud.

Contacts modal

---

app/OzoneConfig.js

feat(Help Articles): Changed help address to reflect new resource

---

app/OzoneConfig.js

feat(reviews): Add config for min number of characters in review

---

app/OzoneConfig.js

chore(Help): Help videos added to config

---

app/js/components/profile/__tests__/ProfileWindow-test.js
karma.conf.js
package.json

A recent update to the profile modal broke its unit test. This change updates the unit test.

chore(profile): fix unit test.

---

app/js/components/notification/UserNotificationDropdown.jsx
app/styles/_notification.scss

fix(notification)btn add hidden span

---

app/js/components/notification/UserNotificationDropdown.jsx
app/js/components/notification/UserNotifications.jsx
app/styles/_notification.scss

notification tweaks

---

app/js/components/notification/UserNotification.jsx
app/styles/_notification.scss
package.json

feat(Marked): added marked to UserNotification.jsx

---

app/styles/_notification.scss

chore(styling): Fix link color in notification dropdown

---

app/js/components/notification/UserNotifications.jsx

fix(Notifications): Notifications are limited to three

---

app/js/components/notification/UserNotification.jsx

fix(Notifications): Chop off notifications at 150 characters

---

app/js/components/notification/UserNotification.jsx

feat(App Notifications): Display name of app sending the notification

---

app/js/components/notification/UserNotification.jsx
app/js/components/notification/UserNotificationDropdown.jsx
app/js/components/notification/UserNotifications.jsx

@clarkjefcoat @mannyrivera2010 @rkenyon1969 @bhalt @akonsowski @wski @tdressel @VLauterbach

Shared Folders Notifications 

---

app/js/components/notification/UserNotification.jsx

@clarkjefcoat @mannyrivera2010 @rkenyon1969

feat(Shared folders): dismiss notifications properly.

---

app/styles/_notification.scss

fix for https://github.com/aml-development/ozp-center/issues/624

fix(styling): Added wordwrap to Notifications #624

---

app/js/constants/messages.js

: Changed variable name and text to reflect that reviews are not to be above FOUO #686

fix(reviews)

---

app/js/constants/messages.js

https://github.com/aml-development/ozp-center/issues/719
@akonsowski @skhtet @blynch11p

enhance(tags): Increase tag length to 30 lines center #719

---

app/js/components/contacts/ContactsWindow.jsx

@blynch11p @rkenyon1969 @lsemesky

fix(contactwindow):removed pin link per request

---

app/js/constants/index.js

added pending delete to constants

---

app/OzoneConfig.js

Updating metrics url

---

app/js/actions/ErrorActions.js
app/js/api/Listings.js
app/js/components/error/ErrorWindow.jsx
app/js/stores/ErrorStore.js
app/styles/_error-window.scss

Display error message when Back-end fails to perform tasks.

JIRA-247: Initial commit for displaying errors on front-end 

---

app/js/constants/messages.js

To be used with the recommender_analytics branch in ozp-center.
@lsemesky @mleeBoeing @rkenyon1969

New constants for recommender usage

---

app/js/stores/ErrorStore.js

This will have to be merged first before center does.
Capture all 500 errors now

Change error code to be all 500 errors

---

app/js/actions/ProfileActions.js
app/js/api/Profile.js
app/js/components/notification/UserNotification.jsx
app/js/components/notification/UserNotificationDropdown.jsx
app/js/components/notification/UserNotifications.jsx
app/js/stores/SelfStore.js
app/js/utils/_.js
app/styles/_notification.scss

requires notificationEndpointUpdate backend branch to test
updated styling for notifications and added behavior where bell icon unread notification becomes read upon clicking.
When individual notification is clicked then it becomes unbolded to identify it has been interacted with. (don't worry I will squash this commit)

Notification endpoint update

---

app/js/components/Date.jsx
app/js/components/Time.jsx

Time should now show in GMT instead of EDT.

Initial commit to display time in Zulu and not EDT

---

app/js/components/Time.jsx

To keep consistency throughout center. Changing GMT to Z

Change GMT to Z

---

app/js/actions/ProfileActions.js
app/js/api/Profile.js
app/js/components/profile/ProfileWindow.jsx
app/styles/_profile-window.scss

Create a switch to toggle email notifications under profile modal
To test:
1. Pull preferences branch
2. In ozp-center directory, open up package.json with any editor
3. Find whereit says ozp-react-commons and change the github link to your local ozp-react-commons preference branch
4. Remove ozp-center/node_modules/ozp-react-commons folder
5. Once removed, do a 'npm install'. Your local copy of ozp-react-commons should be in node_modules now
6. Start up center and go to profile to see the email preferences. Toggle the email switch.
7. Do a GET call to http://localhost:8001/api/self/profile/ and check for "email_notification_flag". The switch should represent the same value as the flag.

Preferences

---

app/js/api/Profile.js
app/js/components/profile/ProfileWindow.jsx
app/styles/_profile-window.scss

Create a switch to toggle listing and subscription notifications under profile modal
To test:
1. In ozp-center directory, open up package.json with any editor
2. Find whereit says ozp-react-commons and change the github link to 'git://github.com/ozone-development/ozp-react-commons#preferences_site'
3. Remove ozp-center/node_modules/ozp-react-commons folder
4. Once removed, do a 'npm install'. This branch of ozp-react-commons should be in node_modules now
5. Start up center and go to profile to see the listing and subscription preferences. Toggle the switches
6. Do a GET call to http://localhost:8001/api/self/profile/ and check for "listing_notification_flag & subscription_notification_flag". The switches should represent the same value as the flag.

Initial commit for site notifications

---

app/styles/_profile-window.scss

Change the background color of the switches in preferences to be green instead of blue.

Change blue background color to green

---

app/js/components/profile/ProfileWindow.jsx
app/styles/_profile-window.scss

Preference text reflect current state of toggle
Test:
When user toggles on preference, descriptive text should indicate "on"
When user toggles off preference, descriptive text should indicate "off"

Preference text reflect current state of toggle

---

app/styles/commons.scss

Issue #862 Center on Git
https://github.com/aml-development/ozp-center/issues/862
Merge before Evan_hud_tour_work branch.

Button Alignment in Tour

---

app/js/components/profile/ProfileWindow.jsx
app/js/components/profile/__tests__/ProfileWindow-test.js

Corrected issues where:
- Users can see deleted listings on profile pages
- Users can see un-approved/disabled listings or other users profile pages
- Modified test file to test for crrect case where the listing is deleted or not
https://github.com/aml-development/ozp-center/issues/865

fix: Profile listings correction

---

app/js/components/profile/CategorySubscriptions.jsx

Removes categories from displaying list when the category has been deleted.
Closes #784 (DI2E)
This affects profile window in HUD and Center.

fix(profile): remove deleted categories from profile

---

app/js/components/notification/NotificationContent.jsx

@aml-development/ozp-backend-team 
This is part of another PR

added action for org steward review requests

---

app/OzoneConfig.js

Change Piwik url to new Piwik instance on aml-metrics-prod server

fix(metrics): fix metrics url to point to udev piwik
