app/js/components/__tests__/WebtopLaunchLink-test.js, karma.conf.js, package.json
1. Update unit test reporting to look like Center's unit test reporting - mocha style red/green x/checkmarks. 
2. Remove trailing slash from webtop launch URL test.
=> fix(unit tests): Update reporting; fix failing launch webtop test.

app/styles/_profile-window.scss
made changes to profile window css to word wrap the app tile in profile window. see [#492](https://github.com/ozone-development/ozp-center/issues/492) bug in center
@clarkjefcoat 
@wski 
@tonyalletag
=> made changes to css to fix bug #492 in center

app/js/api/__tests__/test-listing-data.js
ozp-center, ozp-backend, and ozp-react-commons all have this typo and a PR to match. (Civilian vs Civillian)
@mannyrivera2010 @lsemesky @mleeBoeing @J-Fid
=> Fixing a typo (-react-commons)

app/js/components/profile/ProfileWindow.jsx, app/js/stores/CurrentProfileStore.js
Fix issue where you can see preferences in any profile
Test: Go to profile from menu and see preferences. Then go to a random profile and you shouldn't see any preferences.
=> Fix bug where email preference shows up for any profile

app/js/constants/messages.js
Change the disclaimer text for categories in Create Listing page to say "At least one, no more than three, required".
=> Change the disclaimer for categories

app/js/components/Modal.jsx, app/js/components/contacts/ContactsWindow.jsx, app/js/components/error/ErrorWindow.jsx, app/js/components/profile/ProfileWindow.jsx
The 'title' prop in Modal was inadvertently being used as the 'title' attribute as well.  This PR changes the prop to `modaltitle` instead to remove the unnecessary mouseover title.
@rkenyon1969 @mleeBoeing @lsemesky
=> Profile title

app/js/actions/ProfileActions.js, app/js/api/Profile.js, app/js/components/notification/NotificationContent.jsx, app/js/components/notification/NotificationsModal.jsx, app/js/components/notification/UserNotification.jsx, app/styles/_bootstrap.scss, app/styles/_notification-window.scss, app/styles/_notification.scss, app/styles/commons.scss
Make sure to pull latest backend branch
This builds upon the other PR https://github.com/aml-development/ozp-react-commons/pull/91 . The changes introduced by this PR are 
- Updated styling and notification click functionality to make an unread notification appear much different than a read notification
- Refactored notification content into a shared class so that the text for notifications is the same in the drop down and in the modal
- Corrected the issue with the folder share not working
To test: Jira ticket #460:
(need to have center running and updated ozp-react-commons to point to this branch)
- Create two new notifications for your user
- Click on the drop down
- Both should have bold titles and a blue bar to the left of the notification to indicate that they are unread
- Click on …
=> Notification folder share refactor

app/styles/commons.scss
In center and HUD tour, hover mouse over 'No thanks' button. Button should turn blue. If tabbed to the button should turn blue. Similar to the 'Start the tour' button. Following ticket #847
Need both https://github.com/aml-development/ozp-center/pull/851/files 
and https://github.com/aml-development/ozp-hud/pull/201/files 
for testing
=> added class to commons.scss for blue button

app/styles/commons.scss
Added formatting to popover-header. this only effects "Welcome to" in tour on center and HUD.
No changes should be required for HUD or Center tours.
=> added formatting to popover-header

app/js/constants/index.js, app/js/constants/messages.js
JIRA-713
To test:
After pulling the branch, go to Create/Edit (Submit a Listing) page.
Scroll to the bottom of the page and click Add New under the Contacts section.
The Unsecure Phone section will have an updated message telling the user how to add an extension.
Use case examples for the phone validation:
###-####
###-###-####
(###) ###-####
###-###-#### x##
###-###-#### x###
###-###-#### x####
###-###-#### ext###
etc, etc
'extension' will also work.
(A new field in the create/edit form was deemed unncessary for this feature.  The backend for a phone number already supports upto 50 characters as a string.  The only step needed to allow the user to add an extension was to update the JS REGEX validation to allow x/ext/extension + a number.)
=> feat(phone_ext): Allow users to add a phone extension to listings

app/OzoneConfig.js
Changing URL to use http://xxx.xxx.xxx.xxx/metrtics/
instead of xxx.xxx.xxx.xxx/metrtics-3.0/ to expedite
updating Piwik in the future.
AMLNG-826
**Description**
Rename UDEV Web Analyitics current version to "Metrics"
• The default metrics URL will be changed to http://xxx.xxx.xxx.xxx/metrtics/
**How to test code**
With center running, go to the menu in the top right and select Metrics. 
This should send you to http://172.16.98.67/metrics/
=> Change metrics URL to use IP/Metrics

app/js/components/profile/CategorySubscriptions.jsx, app/js/components/profile/ProfileWindow.jsx, app/js/stores/CategorySubscriptionStore.js
Fix issue where deleting a category leaves "OBJECT NOT FOUND" result in
profile.
Removes invalid objects at store level.
Add call to store from profile window to fix issue where deleting
category and opening profile displays category.
Closes AMLNG-784
**Description** / **Acceptance Criteria** / **How to test code**
Create a new empty Category.
Subscribe to the Category.
View user profile to see new category.
Delete new Category.
View user profile to see error.
=> fix(subscriptions): category subscriptions in profile

app/js/components/profile/ProfileWindow.jsx, app/js/components/profile/__tests__/ProfileWindow-test.js, app/styles/_profile-window.scss
As a user, I want my organization to appear under the username in the Profile Modal so that I can confirm correct information.
Acceptance Criteria:
user organization will appear under the username and above email address on Profile Modal
=> feat(profile): add organizations within profile modal

app/js/components/LoadIndicator.jsx, app/js/components/profile/ProfileWindow.jsx, app/js/components/profile/__tests__/ProfileWindow-test.js, app/js/stores/CurrentProfileStore.js
Add load indicators to various areas of the application, specifically: loading user profiles (listings), tabs in the listing quickview (administration, reviews, notifications), center settings (notifications)
closes AMLNG-808, AMLNG-809, relates to AMLNG-838
**Description**
When loading the user profile, listing quickview, and loading notifications in center settings, update loading process to implement indicator used when Center page first loads.
use site data loading indicator image as placeholder until result set is displayed
same layout as Center page
**How to test code**
Pull additional_load_indicators from ozp-react-commons
Pull additional_load_indicators from ozp-center
Ensure that ozp-center is built with the additional_load_indicators branch of …
=> feat(notifications, quickview, profiles): Additional load indicators

app/js/components/notification/NotificationsModal.jsx, app/styles/_notification-window.scss
closes AMLNG-738
**Description**
As a user I want to be able to scroll through my notifications in the modal so that I don't have an unattractive user experience when I have a lot of notifications.
Implementation suggestion: On the component on the left of the modal that lists all the notifications, set the css for overflow-y to auto.
Open your notifications
Click on "See More"
RESULTS: Notification modal is not scrollable if you have several notifications, causes poor UX
EXPECTED RESULTS: Notification modal is scrollable, scrolling it does not cause the entire page to scroll
**How To Test**
Pull this branch, rebuild ozp-center using this branch instead of ozp-react-commons#master.
=> fix(notification window): added scrollbar to notification list

app/js/components/notification/NotificationContent.jsx
AMLNG-700: Bookmark Folder / un-delete button
Acceptance Criteria:
- ability to restore deleted folder
- undelete button with instructions
- un-delete warning/popup
- notification with link to restore folder
To test:
The `undo_delete_folder` branches are needed from ozp-hud/ozp-center/ozp-backend/ozp-react-commons.
- Log into HUD with any user.
- If the user does not already have bookmarks & bookmark folders, find listings to bookmark, and create some folders.
- Choose the Delete option from any Folder menu.
Results:
Banner is displayed alerting the user the folder was deleted.
The **undo** link will restore the folder
The banner will go away after 10 seconds if not interacted with
The user can click the X in the banner to close it.
- Refresh the page
Results:
A new notification will be …
=> AMLNG-700: Undo delete folder

app/js/components/LoadIndicator.jsx, app/js/stores/CurrentProfileStore.js, app/styles/commons.scss
**Description**
Fix bugs in the profile window on the HUD page.  These bugs are not present when opening the profile on the Center page.
Open the profile window in HUD:
1) Ensure that when loading listings, the spinner icon is centered and animates
2) Ensure that all profile information, including settings and subscriptions, are visible in the window.
Note that you can compare the HUD profile to the correctly working Center profile.  If you spot any differences, then there is a bug/issue.
**How to Test Code**
Pull `fix_profile` from `ozp-center`
Pull `fix_profile` from `ozp-hud`
Pull `fix_profile` from `ozp-react-commons`
Update `package.json` in HUD and Center to point to this branch or your local `ozp-react-commons` repo
=> fix(profile): fix bugs in HUD profile window

app/js/stores/SelfStore.js, app/js/stores/__tests__/CurrentProfileStore-test.js, package.json
Upgrade Jquery dependency from 2.1.1 to 3.2.x.
Modifies tests to support updated Jquery function definitions.
Closes #AMLNG-919
Updates Jquery dependency to remove warning messages in git. 
**How To Test**
Add this branch to your package.json file and install it for center and HUD.
Test full site functionality.
=> fix(dependencies): Upgrade Jquery Dependency

app/js/components/notification/NotificationContent.jsx
AMLOS-490
**Description**     
"Pend for deletion" request should launch notification to org steward.
**Acceptance Criteria**   
Steps to verify:
Pre-req- set jones as owner of Chart Course App
Log on as jones 
Edit Chart Course and set to pend for deletion 
Log on as org steward ( julia) 
RESULTS - Should have a notification that mentions the pending for deletion request.
**How to test code**    
Pull this branch. Pull  pending_deletion_notification_updates from react commons.
As jones, pend a listing for delete. Bigbrother and julia should receive notification.
As jones, cancel the request. Bigbrother and julia should receive notification.
As jones, pend a listing for delete.
As bigbrother and julia, return the request. Jones should receive a notification
As jones, pend a listing for …
=> fix(notifications): pend for delete notifications

app/js/components/notification/UserNotificationDropdown.jsx
Adds reading for new notifications in navbar for users using 508 readout text-to-speech software.
Closes #AMLOS-390
Jaws should read the number in the red circle next to the notification icon in the nav bar.
**how to test**
STR-
Pre-req - Set it up where you have 1 unacknowledged notification. Should display a 1 on the notification bell
Log in to Jaws on top of Apps mall
Tab through to the notifications. 
RESULTS - JAWS reads to user "You have 1 new notification"
=> feat(notifications): correct the reading for new notifications

app/js/components/Modal.jsx
When the browsers back button is pressed, this returns the root's style
class back to normal.
Closes #AMLOS-650
=> fix(modal): Close modal on back button press
